spring.application.name=product-api
server.port=8091
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=alkan
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=my-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.polling.timeout: 10000

logging.level.org.springframework=INFO
logging.level.com.yourproject.product=DEBUG
logging.file.name=logs/product.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
